import type { FoodItem } from "./types";

/**
 * Curated database of everyday foods (per FDA/USDA public nutrition data) with
 * Lose It-style servings — instantly addable without a network request.
 */
export const COMMON_FOODS: FoodItem[] = [
  {
    id: "common-banana",
    name: "Banana",
    servingSize: 118,
    servingLabel: "1 medium (118 g)",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
  },
  {
    id: "common-apple",
    name: "Apple",
    servingSize: 182,
    servingLabel: "1 medium (182 g)",
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
  },
  {
    id: "common-egg",
    name: "Egg, whole",
    servingSize: 50,
    servingLabel: "1 large egg (50 g)",
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 4.8,
  },
  {
    id: "common-chicken-breast",
    name: "Chicken breast, cooked",
    servingSize: 100,
    servingLabel: "100 g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
  },
  {
    id: "common-rice",
    name: "White rice, cooked",
    servingSize: 158,
    servingLabel: "1 cup (158 g)",
    calories: 205,
    protein: 4.3,
    carbs: 45,
    fat: 0.4,
  },
  {
    id: "common-oats",
    name: "Oatmeal, cooked",
    servingSize: 234,
    servingLabel: "1 cup (234 g)",
    calories: 166,
    protein: 5.9,
    carbs: 28,
    fat: 3.2,
  },
  {
    id: "common-greek-yogurt",
    name: "Greek yogurt, plain nonfat",
    servingSize: 170,
    servingLabel: "1 container (170 g)",
    calories: 100,
    protein: 17,
    carbs: 6,
    fat: 0.7,
  },
  {
    id: "common-milk",
    name: "Milk, whole",
    servingSize: 244,
    servingLabel: "1 cup (244 g)",
    calories: 149,
    protein: 7.7,
    carbs: 11.7,
    fat: 7.9,
  },
  {
    id: "common-peanut-butter",
    name: "Peanut butter",
    servingSize: 32,
    servingLabel: "2 tbsp (32 g)",
    calories: 190,
    protein: 8,
    carbs: 7,
    fat: 16,
  },
  {
    id: "common-bread",
    name: "Bread, whole wheat",
    servingSize: 28,
    servingLabel: "1 slice (28 g)",
    calories: 77,
    protein: 3,
    carbs: 14,
    fat: 1,
  },
  {
    id: "common-almonds",
    name: "Almonds",
    servingSize: 28,
    servingLabel: "1 oz (28 g)",
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
  },
  {
    id: "common-olive-oil",
    name: "Olive oil",
    servingSize: 14,
    servingLabel: "1 tbsp (14 g)",
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 13.5,
  },
];
